### PR TITLE
Add flags

### PR DESCRIPTION
**Pull request by Cosetto**
I got this error when trying to import the script:
```
Importing sal/test/menu.sal...
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at SecTool.SecTextTool.<>c__DisplayClass8_0.<<SetText>g__GetTextBlockProp|1>d.MoveNext()
   at SecTool.SecTextTool.SetText(List`1 text, List`1 secCode)
   at SecTool.Program.Main(String[] args)
```
[shukufuku_main.zip](https://github.com/pkuislm/SAS5Tool/files/14967415/shukufuku_main.zip)

### CODE REVIEW

**Comment by pkuislm** [comment]
I see. This exception was thrown because a specific text command it is trying to find (`cmd.ExecutorIndex == 0x03`) does not appear. Usually, this command appears at the end of every text command. 

I'll fix this problem soon(I took a look at `menu.sal.txt` and found that it doesn't contain any text that needs to be translated though.), but before that, you can still import other texts by simply deleting the `menu.sal.txt` inside the input folder, this will let the program to skip the import process of `menu.sal`.

By the way, what do you think about moving these values out of the code as part of the config file? I plan to write them into a json file (the structure of this file is as follows):
```json
{
    "flags":[
        {
            "GameTitle":"Natsuiro Koi Uta",
            "GameTitleJP": "夏彩恋歌",
            "GameID":"natsukoi",
            "FLG_NAME" : 79,
            "FLG_TITLE" : 100,
            "FLG_SELECT" : 112,
        },
        {
            "GameTitle":"Minamijuujisei Renka",
            "GameTitleJP": "南十字星恋歌",
            "GameID":"nankoi",
            "FLG_NAME" : 107,
            "FLG_TITLE" : 130,
            "FLG_SELECT" : 141,
        },
    ]
}
```

**Comment by Cosetto** [comment]
That's nice, I guess it will save us time compiling new version.

**Comment by Cosetto** [comment]
Hey bro, I wonder if you could help me with another engine, it relates to image format. Sorry for asking here.

**Comment by pkuislm** [comment]
> Hey bro, I wonder if you could help me with another engine, it relates to image format. Sorry for asking here.

That sounds interesting. However, I'll be quite busy from May so I'm afraid that I can't help you with that

**Comment by Cosetto** [comment]
> > Hey bro, I wonder if you could help me with another engine, it relates to image format. Sorry for asking here.
> 
> That sounds interesting. However, I'll be quite busy from May so I'm afraid that I can't help you with that

It's about [bExplorer](https://github.com/Inori/FuckGalEngine/tree/master/QLIE/bExplorer/bExplorer) which uses for exporting/importing Qlie engine's .b multi-frame image.
The latest [biman 6](https://vndb.org/v44184) had slightly updated the format, so the tool can't read it.
image
However, GARbro had already been implemented [the code](https://github.com/morkt/GARbro/commit/e0f17747aecc35214a01212554092c292e99b8c0) to read it, but I don't know how to adjust the code into bExplorer.
I have some example files here, back01.b from biman6 (unsupported as mentioned) and title_back01.b from biman 2.5 (supported).

**Pull request merged**
